DEFAULT_PAGE_SIZE = 6

INGREDIENT_NAME_MAX_LENGTH = 128
INGREDIENT_MEASUREMENT_UNIT_MAX_LENGTH = 64

RECIPE_NAME_MAX_LENGTH = 128
RECIPE_IMAGE_UPLOAD_PATH = "recipes/images/"

USER_EMAIL_MAX_LENGTH = 254
USER_USERNAME_MAX_LENGTH = 150
USER_FIRST_NAME_MAX_LENGTH = 150
USER_LAST_NAME_MAX_LENGTH = 150
USER_AVATAR_PATH = "users/"

SHORT_LINK_LENGTH = 8
