# Generated by Django 6.0 on 2025-12-21 16:26

import django.core.validators
import django.db.models.deletion
import recipes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                ("id",
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name="ID")),
                ("name",
                 models.CharField(max_length=128, verbose_name="Название")),
                ("measurement_unit",
                 models.CharField(max_length=64,
                                  verbose_name="Единица измерения")),
            ],
            options={
                "verbose_name": "ингредиент",
                "verbose_name_plural": "Ингредиенты",
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                ("id",
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name="ID")),
                ("name",
                 models.CharField(max_length=128, verbose_name="Название")),
                ("image",
                 models.ImageField(default=None,
                                   null=True,
                                   upload_to="recipes/images/",
                                   verbose_name="Изображение")),
                ("text", models.TextField(verbose_name="Описание")),
                ("cooking_time",
                 models.PositiveSmallIntegerField(
                     validators=[django.core.validators.MinValueValidator(1)],
                     verbose_name="Время приготовления")),
                ("published_at",
                 models.DateTimeField(auto_now_add=True,
                                      verbose_name="Дата публикации")),
                ("short_link",
                 models.SlugField(default=recipes.models.create_slug,
                                  editable=False,
                                  max_length=8,
                                  unique=True)),
                ("author",
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name="recipes",
                                   to=settings.AUTH_USER_MODEL,
                                   verbose_name="Автор")),
            ],
            options={
                "verbose_name": "рецепт",
                "verbose_name_plural": "Рецепты",
            },
        ),
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                ("id",
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name="ID")),
                ("amount",
                 models.PositiveSmallIntegerField(
                     validators=[django.core.validators.MinValueValidator(1)])
                 ),
                ("ingredient",
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name="recipe_ingredients",
                                   to="recipes.ingredient")),
                ("recipe",
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name="recipe_ingredients",
                                   to="recipes.recipe")),
            ],
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                ("id",
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name="ID")),
                ("user",
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name="favorites",
                                   to=settings.AUTH_USER_MODEL)),
                ("recipe",
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name="favorited_by",
                                   to="recipes.recipe")),
            ],
            options={
                "unique_together": {("user", "recipe")},
            },
        ),
        migrations.CreateModel(
            name="ShoppingCart",
            fields=[
                ("id",
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name="ID")),
                ("recipe",
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name="in_shopping_cart_of",
                                   to="recipes.recipe")),
                ("user",
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name="shopping_cart",
                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "unique_together": {("user", "recipe")},
            },
        ),
    ]
