# Generated by Django 6.0 on 2025-12-09 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='desctiption',
            new_name='description',
        ),
    ]
