# Generated by Django 6.0 on 2025-12-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rename_cook_time_recipe_cooking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveIntegerField(default=123),
            preserve_default=False,
        ),
    ]
