# Generated by Django 6.0 on 2025-12-20 15:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_ingredient_options_alter_recipe_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='published',
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
    ]
