# Generated by Django 6.0 on 2025-12-21 15:26

import django.core.validators
import recipes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_rename_published_recipe_published_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_link',
            field=models.SlugField(default=recipes.models.create_slug, editable=False, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
